#!/bin/sh

# Let the process management of Linux take care of the restart so no root privileges are needed.
if (pkill -x domoticz)
then
    echo "Initiated the restart of the domoticz service"
else
    echo "Couldn't find the running  domoticz service named: domoticz"

fi

