#!/bin/sh
cd $1

tar xfz update.tgz
rm update.tgz
rm update.tgz.sha256sum

lowercase(){
    echo "$1" | sed "y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/"
}

OS=`lowercase \`uname -s\``
MACH=`uname -m`

# Restart on OSX
if [ ${OS} = "darwin" ]; then
  launchctl unload /System/Library/LaunchAgents/com.domoticz.server.plist
  echo "Please standby ... (waiting 15 seconds)"
  sleep 15
  launchctl load /System/Library/LaunchAgents/com.domoticz.server.plist
# Try systemd first, else check service.
elif [ `ps -p1 -o comm=` = systemd ]
then
    sudo systemctl stop domoticz.service
    echo "please standby... (waiting 15 seconds)"
    sleep 15
    sudo systemctl start domoticz.service
  elif [ `which service` ]
  then
    sudo service domoticz.sh stop
    echo "please standby... (waiting 15 seconds)"
    sleep 15
    sudo service domoticz.sh start
  else
        echo "No supported init process management tool like service or systemctl available"
fi

