#!/bin/sh
cd $1

tar xfz update.tgz
rm update.tgz
rm update.tgz.sha256sum

lowercase(){
    echo "$1" | sed "y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/"
}

OS=`lowercase \`uname -s\``
MACH=`uname -m`

# Restart on OSX
if [ ${OS} = "darwin" ]; then
  launchctl unload /System/Library/LaunchAgents/com.domoticz.server.plist
  echo "Please standby ... (waiting 15 seconds)"
  sleep 15
  launchctl load /System/Library/LaunchAgents/com.domoticz.server.plist
# Let the process management of Linux take care of the restart so no root privileges are needed.
elif (pkill -x domoticz)
then
    echo "Initiated the restart of the domoticz service"
else
    echo "Couldn't find the running  domoticz service, please restart the domoticz service to finish upgrade."

fi
